import fs from 'fs'
import path from 'path'
import { Plugin } from 'vite';

type MdxExtracted = {
    meta: {
        [key: string]: any;
    };
    relativePath: string;
    slug: string;
}

/**
 * 
 * Get's the type of a primitive value
 */
function getPrimitiveType(value: any) {
    const type = typeof value
    if (type === 'string' || type === 'number' || type === 'boolean') {
        return type
    }
    return null
}

/**
 * Parses YAML-style frontmatter from raw MDX file content.
 * Extracts all key: value pairs between --- delimiters.
 */
function parseFrontmatter(fileContent: string) {
    const match = fileContent.match(/^---\s*\n([\s\S]*?)\n---/)

    if (!match) return {}

    const raw = match[1]
    const meta: { [key: string]: any } = {}

    for (const line of raw.split('\n')) {
        const colonIndex = line.indexOf(':')
        if (colonIndex === -1) continue

        const key = line.slice(0, colonIndex).trim()
        const value = line.slice(colonIndex + 1).trim().replace(/^['"]|['"]$/g, '')

        if (key) meta[key] = value
    }

    return meta
}

/**
 * Converts a directory name to a camelCase array name.
 * e.g. "blog-posts" -> "blogPostsMeta"
 */
function toMetaName(dirName: string) {
    const camel = dirName.replace(/-([a-z])/g, (_, c) => c.toUpperCase())
    return `${camel}Meta`
}

/**
 * Generates the output file content for a given category.
 * Each MDX file becomes an object with its frontmatter + a lazy component import.
 */
function generateContentCategory(category: string, entries: MdxExtracted[]) {
    const metaName = toMetaName(category)

    const objects = entries.map(({ meta, relativePath, slug }: { meta: {}, relativePath: string, slug: string }) => {
        const metaFields = Object.entries(meta)
            .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
            .join(',\n')

        return `{
        ${metaFields},
        slug: ${JSON.stringify(slug)},
        path: ${JSON.stringify(relativePath)},
        component: () => import("${relativePath}")
    }`})

    return `export const ${metaName}: ContentMeta[] = [${objects.join(',\n')}]`
}

/**
 * Vite plugin: scans content/ subdirectories for MDX files,
 * parses frontmatter, and generates one index file per category
 * into src/generated/.
 *
 * Usage in vite.config.js:
 *   import contentIndex from './vite-plugin-content-index.js'
 *   export default { plugins: [contentIndex()] }
 *
 * Options:
 *   contentDir  - path to content folder (default: 'content')
 *   outputDir   - where to write generated files (default: 'src/generated')
 */
export default function contentIndexPlugin(options?: { contentDir: string, outputDir: string }):
    Plugin {
    const {
        contentDir = 'src/content',
        outputDir = 'src',
    } = options || {}

    function run(root: string) {
        const contentPath = path.resolve(root, contentDir)
        const outputPath = path.resolve(root, outputDir)

        if (!fs.existsSync(contentPath)) return

        fs.mkdirSync(outputPath, { recursive: true })

        const entries = fs.readdirSync(contentPath, { withFileTypes: true })
        const subDirs = entries.filter(e => e.isDirectory())

        const blocks = []

        for (const dir of subDirs) {
            const category = dir.name
            const categoryPath = path.join(contentPath, category)
            const files = fs.readdirSync(categoryPath).filter(f => f.endsWith('.mdx'))

            const parsed = files.map(file => {
                const filePath = path.join(categoryPath, file)
                const content = fs.readFileSync(filePath, 'utf8')
                const meta = parseFrontmatter(content)
                const slug = file.replace(/\.mdx$/, '')
                const relativePath = `../${contentDir}/${category}/${file}`

                return { meta, relativePath, slug }
            })

            blocks.push(generateContentCategory(category, parsed))
        }

        const monoFile = `// Auto-generated by vite-plugin-content-index. Do not edit manually.\nimport { ContentMeta } from '../plugins/content-index/types'
            \n${blocks.join('\n')}`
        const outFile = path.join(outputPath, 'content.gen.ts')
        fs.writeFileSync(outFile, monoFile)

        console.log(`[content-index] Generated ${outFile} (${subDirs.length} categories)`)
    }

    return {
        name: 'vite-plugin-content-index',

        // Runs once when Vite starts
        buildStart() {
            run(process.cwd())
        },

        // Watches content folder in dev mode and regenerates on change
        configureServer(server) {
            const contentPath = path.resolve(process.cwd(), contentDir)

            server.watcher.add(contentPath)

            server.watcher.on('change', file => {
                if (file.startsWith(contentPath)) {
                    run(process.cwd())
                    // Trigger HMR for any module that imported a generated file
                    server.moduleGraph.invalidateAll()
                }
            })

            server.watcher.on('add', file => {
                if (file.startsWith(contentPath)) run(process.cwd())
            })

            server.watcher.on('unlink', file => {
                if (file.startsWith(contentPath)) run(process.cwd())
            })
        }
    }
}