/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicStatsRouteImport } from './routes/_public/stats'
import { Route as PublicBlogRouteRouteImport } from './routes/_public/blog/route'
import { Route as PublicBlogIndexRouteImport } from './routes/_public/blog/index'
import { Route as PublicProjectsProjectSlugRouteImport } from './routes/_public/projects/$projectSlug'
import { Route as PublicBlogBlogSlugRouteImport } from './routes/_public/blog/$blogSlug'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicStatsRoute = PublicStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlogRouteRoute = PublicBlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicBlogRouteRoute,
} as any)
const PublicProjectsProjectSlugRoute =
  PublicProjectsProjectSlugRouteImport.update({
    id: '/projects/$projectSlug',
    path: '/projects/$projectSlug',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicBlogBlogSlugRoute = PublicBlogBlogSlugRouteImport.update({
  id: '/$blogSlug',
  path: '/$blogSlug',
  getParentRoute: () => PublicBlogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/$': typeof SplatRoute
  '/blog': typeof PublicBlogRouteRouteWithChildren
  '/stats': typeof PublicStatsRoute
  '/blog/$blogSlug': typeof PublicBlogBlogSlugRoute
  '/projects/$projectSlug': typeof PublicProjectsProjectSlugRoute
  '/blog/': typeof PublicBlogIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/stats': typeof PublicStatsRoute
  '/': typeof PublicIndexRoute
  '/blog/$blogSlug': typeof PublicBlogBlogSlugRoute
  '/projects/$projectSlug': typeof PublicProjectsProjectSlugRoute
  '/blog': typeof PublicBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_public/blog': typeof PublicBlogRouteRouteWithChildren
  '/_public/stats': typeof PublicStatsRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/blog/$blogSlug': typeof PublicBlogBlogSlugRoute
  '/_public/projects/$projectSlug': typeof PublicProjectsProjectSlugRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/blog'
    | '/stats'
    | '/blog/$blogSlug'
    | '/projects/$projectSlug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/stats'
    | '/'
    | '/blog/$blogSlug'
    | '/projects/$projectSlug'
    | '/blog'
  id:
    | '__root__'
    | '/_public'
    | '/$'
    | '/_public/blog'
    | '/_public/stats'
    | '/_public/'
    | '/_public/blog/$blogSlug'
    | '/_public/projects/$projectSlug'
    | '/_public/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/stats': {
      id: '/_public/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof PublicStatsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blog': {
      id: '/_public/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicBlogRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicBlogRouteRoute
    }
    '/_public/projects/$projectSlug': {
      id: '/_public/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof PublicProjectsProjectSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blog/$blogSlug': {
      id: '/_public/blog/$blogSlug'
      path: '/$blogSlug'
      fullPath: '/blog/$blogSlug'
      preLoaderRoute: typeof PublicBlogBlogSlugRouteImport
      parentRoute: typeof PublicBlogRouteRoute
    }
  }
}

interface PublicBlogRouteRouteChildren {
  PublicBlogBlogSlugRoute: typeof PublicBlogBlogSlugRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
}

const PublicBlogRouteRouteChildren: PublicBlogRouteRouteChildren = {
  PublicBlogBlogSlugRoute: PublicBlogBlogSlugRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
}

const PublicBlogRouteRouteWithChildren = PublicBlogRouteRoute._addFileChildren(
  PublicBlogRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicBlogRouteRoute: typeof PublicBlogRouteRouteWithChildren
  PublicStatsRoute: typeof PublicStatsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicProjectsProjectSlugRoute: typeof PublicProjectsProjectSlugRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicBlogRouteRoute: PublicBlogRouteRouteWithChildren,
  PublicStatsRoute: PublicStatsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicProjectsProjectSlugRoute: PublicProjectsProjectSlugRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
