name: Deploy to Pi
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          envs: PI_SOURCE_DIR,PI_PUBLIC_HTML
          script: |
            cd $PI_SOURCE_DIR
            git pull origin main
            npm install
            npm run build
            rm -rf $PI_PUBLIC_HTML/*
            cp -r  dist/* $PI_PUBLIC_HTML/